### ISSUE TITLE
Unit tests are failing when run integrated with other components: could not install deps due to version conflict

### ISSUE THREAD

**Issue by italovalcy** [kytos/of_core#126]
Hi team,

I'm running unit tests for maintenance using gitlab-ci and the following commands:
```
basic-testing:
  stage: test
  image: "python:3.6"
  script:
    - pip install --upgrade pip tox
    - git config --global url."https://github.com".insteadOf git://github.com
    - sed -e 's/^::1/#::1/g' /etc/hosts > /tmp/hosts && cat /tmp/hosts > /etc/hosts
    - for proj in kytos kytos-utils of_core storehouse of_lldp flow_manager topology pathfinder mef_eline maintenance; do git clone https://github.com/kytos/$proj; cd $proj; tox; cd ..; done
```

The test is failing with the following error:
```
ERROR: Cannot install -r requirements/dev.txt (line 7) and docutils==0.16 because these package versions have conflicting dependencies.
948The conflict is caused by:
949    The user requested docutils==0.16
950    kytos 2020.2 depends on docutils==0.17
951To fix this you could try to:
9521. loosen the range of package versions you've specified
9532. remove package versions to allow pip attempt to solve the dependency conflict
954ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
955WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
956You should consider upgrading via the '/builds/italo/kytos-pipeline/of_core/.tox/py36/bin/python -m pip install --upgrade pip' command.
957=================================== log end ====================================
958ERROR: could not install deps [-Urrequirements/dev.txt]; v = InvocationError('/builds/italo/kytos-pipeline/of_core/.tox/py36/bin/python -m pip install -Urrequirements/dev.txt', 1)
959
```
